version: "3.9"

services:

  nginx:
    container_name: sae-nginx
    image: nginx:latest
    ports:
      - "8787:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: sae-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  mysql:
    container_name: sae-mysql
    image: mysql:8
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SAEStarter
  
  phpmyadmin:
    container_name: sae-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8788:80"
    depends_on:
      - mysql

volumes:
  database:
